language: python

python:
    - 3.9

services:
  - mysql
  
env: 
  - FLASK_APP="store", DB_USER="root", DB_PASSWORD="", DB_HOST="127.0.0.1:3306"
   
install: 
  - mysql -e 'CREATE DATABASE store;'
  - cd store_app 
  - pip install .
  - coverage run --source=store -m pytest
  - pylint ./store | grep rated

after:
  - covrealls

service_name: travis-pro
repo_token: New7B0MZdsYf5vo72SIvfsJqTC4gY4U0B

