language: python

python:
    - 3.9

install: 
  - cd store_app 
  - pip install .
  
script:
  - export FLASK_APP=store
  - flask run
  - pip freeze
  - pytest

service_name: travis-pro
repo_token: New7B0MZdsYf5vo72SIvfsJqTC4gY4U0B
