language: python

python:
    - 3.9

services:
  - mysql
  
env: 
  - FLASK_APP=store

before:
  - mysql -e 'create database store;'
  
install: 
  - mysql \connect root@127.0.0.1:3306
  - cd store_app 
  - pip install .
  - flask db init
  - flask db migrate
  - flask db upgrade
  - flask seed
  - pip install coveralls
  - coverage run --source=store -m pytest
script:
  - pytest
after:
  - covrealls

service_name: travis-pro
repo_token: New7B0MZdsYf5vo72SIvfsJqTC4gY4U0B
