language: python

python:
    - 3.9

services:
  - mysql
  
env: 
  - FLASK_APP="store"
   
install: 
  - mysql -e 'CREATE DATABASE store;'
  - cd store_app 
  - pip install .
  - flask db upgrade
  - flask db migrate
  - flask db upgrade
  - flask seed
  - cd ..
  - pip install coveralls
  - coverage run --source=store -m pytest
script:
  - pytest
  - covrealls
after:
  - covrealls

service_name: travis-pro
repo_token: New7B0MZdsYf5vo72SIvfsJqTC4gY4U0B
