"""empty message

Revision ID: 94a7eab87e7e
Revises: b811dcc17ce9
Create Date: 2023-03-07 19:10:20.659507

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '94a7eab87e7e'
down_revision = 'b811dcc17ce9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_product', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
