"""empty message

Revision ID: b811dcc17ce9
Revises: 0c07e582c7e7
Create Date: 2023-03-05 11:11:28.417349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b811dcc17ce9'
down_revision = '0c07e582c7e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_product', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
